engines:
  checkstyle:
    enabled: true
    channel: "beta"
    # ... CONFIG CONTENT ...
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SingleLineJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTagContinuationIndentationCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.MethodNameCheck:
        enabled: false
# ... CONFIG CONTENT ...

ratings:
  paths:
  - "**.java"
