language: java
dist: trusty
services:
  - mysql
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
jdk:
  - oraclejdk8
  
addons:
  mariadb: '10.0'
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - mvn clean test jacoco:report coveralls:report
